# ==============================================================================
# Merged Lakeflow Source: cockroachdb
# ==============================================================================
# This file is auto-generated by scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Dict,
    Iterator,
    List,
)
import json

from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *
import psycopg2
import psycopg2.extras


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # libs/utils.py
    ########################################################

    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None
        # Handle complex types
        if isinstance(field_type, StructType):
            # Validate input for StructType
            if not isinstance(value, dict):
                raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
            # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
            if value == {}:
                raise ValueError(
                    f"field in StructType cannot be an empty dict. Please assign None as the default value instead."
                )
            # For StructType, recursively parse fields into a Row
            field_dict = {}
            for field in field_type.fields:
                # When a field does not exist in the input:
                # 1. set it to None when schema marks it as nullable
                # 2. Otherwise, raise an error.
                if field.name in value:
                    field_dict[field.name] = parse_value(
                        value.get(field.name), field.dataType
                    )
                elif field.nullable:
                    field_dict[field.name] = None
                else:
                    raise ValueError(
                        f"Field {field.name} is not nullable but not found in the input"
                    )

            return Row(**field_dict)
        elif isinstance(field_type, ArrayType):
            # For ArrayType, parse each element in the array
            if not isinstance(value, list):
                # Handle edge case: single value that should be an array
                if field_type.containsNull:
                    # Try to convert to a single-element array if nulls are allowed
                    return [parse_value(value, field_type.elementType)]
                else:
                    raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
            return [parse_value(v, field_type.elementType) for v in value]
        elif isinstance(field_type, MapType):
            # Handle MapType - new support
            if not isinstance(value, dict):
                raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
            return {
                parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
                for k, v in value.items()
            }
        # Handle primitive types with more robust error handling and type conversion
        try:
            if isinstance(field_type, StringType):
                # Don't convert None to "None" string
                return str(value) if value is not None else None
            elif isinstance(field_type, (IntegerType, LongType)):
                # Convert numeric strings and floats to integers
                if isinstance(value, str) and value.strip():
                    # Handle numeric strings
                    if "." in value:
                        return int(float(value))
                    return int(value)
                elif isinstance(value, (int, float)):
                    return int(value)
                raise ValueError(f"Cannot convert {value} to integer")
            elif isinstance(field_type, FloatType) or isinstance(field_type, DoubleType):
                # New support for floating point types
                if isinstance(value, str) and value.strip():
                    return float(value)
                return float(value)
            elif isinstance(field_type, DecimalType):
                # New support for Decimal type

                if isinstance(value, str) and value.strip():
                    return Decimal(value)
                return Decimal(str(value))
            elif isinstance(field_type, BooleanType):
                # Enhanced boolean conversion
                if isinstance(value, str):
                    lowered = value.lower()
                    if lowered in ("true", "t", "yes", "y", "1"):
                        return True
                    elif lowered in ("false", "f", "no", "n", "0"):
                        return False
                return bool(value)
            elif isinstance(field_type, DateType):
                # New support for DateType
                if isinstance(value, str):
                    # Try multiple date formats
                    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                        try:
                            return datetime.strptime(value, fmt).date()
                        except ValueError:
                            continue
                    # ISO format as fallback
                    return datetime.fromisoformat(value).date()
                elif isinstance(value, datetime):
                    return value.date()
                raise ValueError(f"Cannot convert {value} to date")
            elif isinstance(field_type, TimestampType):
                # Enhanced timestamp handling
                if isinstance(value, str):
                    # Handle multiple timestamp formats including Z and timezone offsets
                    if value.endswith("Z"):
                        value = value.replace("Z", "+00:00")
                    try:
                        return datetime.fromisoformat(value)
                    except ValueError:
                        # Try additional formats if ISO format fails
                        for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                            try:
                                return datetime.strptime(value, fmt)
                            except ValueError:
                                continue
                elif isinstance(value, (int, float)):
                    # Handle Unix timestamps
                    return datetime.fromtimestamp(value)
                elif isinstance(value, datetime):
                    return value
                raise ValueError(f"Cannot convert {value} to timestamp")
            else:
                # Check for custom UDT handling
                if hasattr(field_type, "fromJson"):
                    # Support for User Defined Types that implement fromJson
                    return field_type.fromJson(value)
                raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            # Add context to the error
            raise ValueError(
                f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}"
            )


    ########################################################
    # sources/cockroachdb/cockroachdb.py
    ########################################################

    class LakeflowConnect:
        """CockroachDB connector using sinkless changefeeds for CDC."""

        def __init__(self, options: Dict[str, str]) -> None:
            """
            Initialize the CockroachDB connector.

            Args:
                options: Dictionary containing:
                    - host: CockroachDB host
                    - port: CockroachDB port (default: 26257)
                    - database: Database name
                    - user: Username
                    - password: Password (can be empty for insecure mode)
                    - sslmode: SSL mode (default: 'require')
                    - schema: Schema name (default: 'public')
            """
            self.conn = None  # Initialize conn first for __del__

            self.host = options.get("host")
            self.port = int(options.get("port", "26257"))
            self.database = options.get("database")
            self.user = options.get("user")
            self.password = options.get("password", "")  # Empty password is valid for insecure mode
            self.sslmode = options.get("sslmode", "require")
            self.schema = options.get("schema", "public")

            # Validate required parameters (password can be empty)
            if not all([self.host, self.database, self.user is not None]):
                raise ValueError("Missing required connection parameters: host, database, user")

            self._init_connection()

        def _init_connection(self) -> None:
            """Initialize connection to CockroachDB."""
            try:
                self.conn = psycopg2.connect(
                    host=self.host,
                    port=self.port,
                    database=self.database,
                    user=self.user,
                    password=self.password,
                    sslmode=self.sslmode
                )
                self.conn.set_session(autocommit=True)
            except Exception as e:
                raise ConnectionError(f"Failed to connect to CockroachDB: {str(e)}")

        def _ensure_connection(self) -> None:
            """Ensure connection is alive, reconnect if needed."""
            try:
                if self.conn is None or self.conn.closed:
                    self._init_connection()
            except Exception:
                self._init_connection()

        def list_tables(self) -> List[str]:
            """
            List all tables in the specified schema.

            Returns:
                List of table names
            """
            self._ensure_connection()

            query = """
                SELECT table_name 
                FROM information_schema.tables 
                WHERE table_schema = %s
                  AND table_type = 'BASE TABLE'
                ORDER BY table_name
            """

            with self.conn.cursor() as cur:
                cur.execute(query, (self.schema,))
                tables = [row[0] for row in cur.fetchall()]

            return tables

        def get_table_schema(
            self, table_name: str, table_options: Dict[str, str]
        ) -> StructType:
            """
            Get the Spark schema for a CockroachDB table.

            Args:
                table_name: Name of the table
                table_options: Additional options (not used currently)

            Returns:
                StructType representing the table schema
            """
            # Validate table exists
            if table_name not in self.list_tables():
                raise ValueError(f"Table '{table_name}' not found in schema '{self.schema}'")

            self._ensure_connection()

            query = """
                SELECT 
                    column_name,
                    data_type,
                    character_maximum_length,
                    numeric_precision,
                    numeric_scale,
                    is_nullable
                FROM information_schema.columns
                WHERE table_schema = %s 
                  AND table_name = %s
                ORDER BY ordinal_position
            """

            with self.conn.cursor() as cur:
                cur.execute(query, (self.schema, table_name))
                columns = cur.fetchall()

            fields = []
            for col in columns:
                col_name, data_type, char_max_len, num_precision, num_scale, is_nullable = col
                nullable = (is_nullable == 'YES')
                spark_type = self._map_cockroachdb_type_to_spark(
                    data_type, char_max_len, num_precision, num_scale
                )
                fields.append(StructField(col_name, spark_type, nullable))

            # Add CDC metadata fields (connector-added, not in source database)
            # These are derived from CockroachDB's native changefeed columns:
            #   - CockroachDB returns: (key, value, updated, topic)
            #   - Connector adds: _cdc_key, _cdc_updated, _cdc_operation
            # This follows Lakeflow CDC conventions for Delta Lake integration
            fields.append(StructField("_cdc_key", ArrayType(StringType()), True))      # Mapped from changefeed 'key' column
            fields.append(StructField("_cdc_updated", StringType(), True))             # Mapped from changefeed 'updated' column
            fields.append(StructField("_cdc_operation", StringType(), True))           # Derived from changefeed 'value' column

            return StructType(fields)

        def _map_cockroachdb_type_to_spark(
            self, data_type: str, char_max_len: int, num_precision: int, num_scale: int
        ) -> Any:
            """Map CockroachDB/PostgreSQL types to Spark types."""
            data_type_lower = data_type.lower()

            # Integer types
            if data_type_lower in ('bigint', 'int8', 'serial', 'bigserial'):
                return LongType()
            elif data_type_lower in ('integer', 'int', 'int4', 'int2', 'smallint'):
                return LongType()  # Prefer LongType over IntegerType

            # Floating point types
            elif data_type_lower in ('double precision', 'float8', 'float', 'real', 'float4'):
                return DoubleType()

            # Decimal types
            elif data_type_lower in ('numeric', 'decimal'):
                if num_precision and num_scale is not None:
                    return DecimalType(num_precision, num_scale)
                else:
                    return DecimalType(38, 18)  # Default precision

            # Boolean
            elif data_type_lower in ('boolean', 'bool'):
                return BooleanType()

            # String types
            elif data_type_lower in ('character varying', 'varchar', 'character', 'char', 'text', 'string'):
                return StringType()

            # Binary types
            elif data_type_lower in ('bytea', 'bytes'):
                return BinaryType()

            # Date and time types
            elif data_type_lower == 'date':
                return DateType()
            elif data_type_lower in ('timestamp without time zone', 'timestamp'):
                return TimestampType()
            elif data_type_lower in ('timestamp with time zone', 'timestamptz'):
                return TimestampType()
            elif data_type_lower in ('time', 'time without time zone', 'time with time zone'):
                return StringType()  # Represent time as string
            elif data_type_lower == 'interval':
                return StringType()

            # UUID
            elif data_type_lower == 'uuid':
                return StringType()

            # Network types
            elif data_type_lower in ('inet', 'cidr', 'macaddr'):
                return StringType()

            # JSON types
            elif data_type_lower in ('json', 'jsonb'):
                return StringType()  # Store JSON as string

            # Array types
            elif data_type_lower == 'ARRAY':
                return ArrayType(StringType())  # Default to string array

            # Default fallback
            else:
                return StringType()

        def read_table_metadata(
            self, table_name: str, table_options: Dict[str, str]
        ) -> Dict[str, Any]:
            """
            Get metadata for a table.

            Args:
                table_name: Name of the table
                table_options: Additional options (not used currently)

            Returns:
                Dictionary with metadata:
                    - primary_keys: List of primary key column names
                    - cursor_field: Field to use for cursor (_cdc_updated)
                    - ingestion_type: Always 'cdc' for changefeeds
            """
            # Validate table exists
            if table_name not in self.list_tables():
                raise ValueError(f"Table '{table_name}' not found in schema '{self.schema}'")

            self._ensure_connection()

            # Get primary key columns
            pk_query = """
                SELECT kcu.column_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu 
                  ON tc.constraint_name = kcu.constraint_name
                  AND tc.table_schema = kcu.table_schema
                  AND tc.table_name = kcu.table_name
                WHERE tc.constraint_type = 'PRIMARY KEY'
                  AND tc.table_schema = %s
                  AND tc.table_name = %s
                ORDER BY kcu.ordinal_position
            """

            with self.conn.cursor() as cur:
                cur.execute(pk_query, (self.schema, table_name))
                pk_columns = [row[0] for row in cur.fetchall()]

            if not pk_columns:
                raise ValueError(f"Table '{table_name}' has no primary key. CockroachDB changefeeds require a primary key.")

            return {
                "primary_keys": pk_columns,
                "cursor_field": "_cdc_updated",  # Use CDC timestamp as cursor
                "ingestion_type": "cdc"  # All CockroachDB tables support CDC via changefeeds
            }

        def read_table(
            self, table_name: str, start_offset: Dict, table_options: Dict[str, str]
        ) -> (Iterator[Dict], Dict):
            """
            Read table data using CockroachDB changefeed.

            Args:
                table_name: Name of the table
                start_offset: Starting cursor position (timestamp)
                table_options: Additional options:
                    - cursor: Resume cursor (CockroachDB timestamp)
                    - include_diff: Include before/after values (boolean)
                    - select_query: Custom SELECT for filtered changefeed
                    - resolved_interval: Resolved timestamp interval (default: '10s')
                    - batch_size: Number of events to read before returning (default: 1000)

            Returns:
                Iterator of change events and end offset
            """
            # Validate table exists
            if table_name not in self.list_tables():
                raise ValueError(f"Table '{table_name}' not found in schema '{self.schema}'")

            # Parse options
            cursor = start_offset.get("cursor") if start_offset else None
            include_diff = table_options.get("include_diff", "false").lower() == "true"
            select_query = table_options.get("select_query")
            resolved_interval = table_options.get("resolved_interval", "10s")
            batch_size = int(table_options.get("batch_size", "1000"))

            # Override cursor from table_options if provided
            if table_options.get("cursor"):
                cursor = table_options.get("cursor")

            # Build changefeed query
            changefeed_options = []

            # Include initial scan (existing rows) if requested
            # 'only' = return existing rows then stop (batch mode - no streaming options)
            # 'yes' = return existing rows then stream new changes (CDC mode - includes streaming options)
            initial_scan = table_options.get("initial_scan", "only")  # Default to 'only' for faster testing

            if initial_scan.lower() == "only":
                # Batch/snapshot mode: initial_scan='only' cannot be combined with updated/resolved
                changefeed_options.append(f"initial_scan='only'")
                # Don't add 'updated' or 'resolved' - they're incompatible with initial_scan='only'
            elif initial_scan.lower() == "yes":
                # Streaming CDC mode: include streaming options
                changefeed_options.append(f"initial_scan='yes'")
                changefeed_options.append("updated")  # Include timestamps
                changefeed_options.append(f"resolved='{resolved_interval}'")
            else:
                # Default streaming mode (no initial_scan specified)
                changefeed_options.append("updated")  # Include timestamps
                changefeed_options.append(f"resolved='{resolved_interval}'")

            if include_diff:
                changefeed_options.append("diff")

            # Add split_column_families for tables with multiple column families
            # This is required for some tables (like YCSB usertable)
            split_families = table_options.get("split_column_families", "true")
            if split_families.lower() == "true":
                changefeed_options.append("split_column_families")

            if cursor:
                changefeed_options.append(f"cursor='{cursor}'")

            options_str = ", ".join(changefeed_options)

            # Determine changefeed target
            if select_query:
                # Use CDC query (filtered changefeed)
                target = f"({select_query})"
            else:
                # Use table name
                if self.schema != 'public':
                    target = f"{self.schema}.{table_name}"
                else:
                    target = table_name

            changefeed_query = f"EXPERIMENTAL CHANGEFEED FOR {target} WITH {options_str}"

            # Debug logging (can be disabled in production)
            import os
            if os.getenv("DEBUG_CHANGEFEED"):
                print(f"[DEBUG] Changefeed query: {changefeed_query}")
                print(f"[DEBUG] Batch size: {batch_size}")
                print(f"[DEBUG] Start offset: {start_offset}")

            # Execute changefeed
            self._ensure_connection()

            def event_generator():
                """Generator that yields changefeed events.

                CockroachDB changefeed returns different columns based on options:
                    - Without 'updated': (key, value) - 2 columns
                    - With 'updated': (key, value, updated, topic) - 4 columns
                """
                changefeed_cursor = self.conn.cursor()
                changefeed_cursor.execute(changefeed_query)

                event_count = 0
                last_resolved = None

                # Detect if 'updated' option is used (affects result structure)
                has_updated = initial_scan.lower() != "only"  # 'only' mode doesn't support 'updated'

                try:
                    for row in changefeed_cursor:
                        if has_updated:
                            # Format with 'updated': (table, key, value, updated, topic)
                            table_name = row[0]
                            key_json = row[1]
                            value_json = row[2]
                            updated = row[3]
                            topic = row[4] if len(row) > 4 else None

                            # Check if this is a resolved timestamp event
                            if key_json is None and value_json is None:
                                # Resolved timestamp row - use as watermark
                                last_resolved = updated
                                continue
                        else:
                            # Format without 'updated': (table, key, value)
                            table_name = row[0]
                            key_json = row[1]
                            value_json = row[2]
                            updated = None  # No timestamp in initial_scan='only' mode
                            topic = None

                        # Parse JSON columns (handle None, empty strings, and memoryview objects)
                        # psycopg2 may return bytea columns as memoryview objects
                        def parse_json_column(json_data):
                            """Parse JSON from string, bytes, or memoryview."""
                            if json_data is None:
                                return None

                            # Convert memoryview or bytes to string
                            if isinstance(json_data, memoryview):
                                json_data = json_data.tobytes().decode('utf-8')
                            elif isinstance(json_data, bytes):
                                json_data = json_data.decode('utf-8')

                            # Check for empty or whitespace-only strings
                            if not isinstance(json_data, str) or json_data.strip() == '':
                                return None

                            try:
                                return json.loads(json_data)
                            except json.JSONDecodeError:
                                return None

                        key = parse_json_column(key_json) or []
                        value = parse_json_column(value_json)

                        # Transform to standardized format using native columns
                        transformed_event = self._transform_changefeed_event_native(
                            key, value, updated, include_diff
                        )
                        yield transformed_event

                        event_count += 1

                        # Stop after batch_size events
                        if event_count >= batch_size:
                            break
                finally:
                    changefeed_cursor.close()

                # Return the last resolved timestamp as the new cursor
                return last_resolved

            # Create iterator and collect events
            events = []
            last_resolved = None

            try:
                gen = event_generator()
                for event in gen:
                    events.append(event)
            except StopIteration as e:
                last_resolved = e.value if hasattr(e, 'value') else None

            # Determine end offset
            end_offset = start_offset.copy() if start_offset else {}
            if last_resolved:
                end_offset["cursor"] = last_resolved

            return iter(events), end_offset

        def _transform_changefeed_event_native(
            self, key: list, value: Dict, updated: str, include_diff: bool
        ) -> Dict:
            """
            Transform CockroachDB's native changefeed columns into Lakeflow CDC format.

            CockroachDB changefeeds natively return different columns based on options:
                - Without 'updated' option: (key, value) - 2 columns
                - With 'updated' option: (key, value, updated, topic) - 4 columns

            This method maps them to Lakeflow CDC conventions (fields added by connector):
                - _cdc_key: Mapped from 'key' column
                - _cdc_updated: Mapped from 'updated' column (or None if not available)
                - _cdc_operation: Derived from 'value' column content

            Args:
                key: Primary key values (from changefeed 'key' column)
                value: Row data (from changefeed 'value' column)
                updated: MVCC timestamp (from changefeed 'updated' column, or None for snapshot queries)
                include_diff: Whether diff (before/after) is included

            Returns:
                Dictionary with original columns + connector-added CDC metadata fields
            """
            result = {}

            # Add CDC metadata fields (connector-added, not in source database)
            result["_cdc_key"] = key                    # Mapped from changefeed 'key' column
            result["_cdc_updated"] = updated            # Mapped from changefeed 'updated' column (None in snapshot mode)

            # Derive operation type from changefeed 'value' column content
            # (This field is added by the connector for Lakeflow CDC compatibility)
            if value is None:
                # DELETE operation - changefeed returns null value for deletes
                result["_cdc_operation"] = "DELETE"
                # For deletes, we only have the key (no row data)
            elif include_diff and "before" in value:
                # UPDATE operation (has both before and after)
                result["_cdc_operation"] = "UPDATE"
                after = value.get("after", {})
                result.update(after)  # Add original table columns
            else:
                # INSERT or UPDATE (only after value available)
                after = value.get("after") if value else None
                if after:
                    result["_cdc_operation"] = "INSERT"  # Could be UPDATE without diff
                    result.update(after)  # Add original table columns

            return result

        def __del__(self):
            """Close connection when object is destroyed."""
            if self.conn and not self.conn.closed:
                self.conn.close()


    ########################################################
    # pipeline/lakeflow_python_source.py
    ########################################################

    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            records, offset = self.lakeflow_connect.read_table(
                self.options["tableName"], start, self.options
            )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(table, self.options)
                all_records.append({"tableName": table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        def __init__(self, options):
            self.options = options
            self.lakeflow_connect = LakeflowConnect(options)

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options["tableName"]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField("tableName", StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                # Assuming the LakeflowConnect interface uses get_table_schema, not get_table_details
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
