"""
CockroachDB CDC Integration Tests

Tests all CDC scenarios (8 combinations) using both Autoloader and Iterator patterns.
Compatible with the existing LakeflowConnect test framework (test_suite.py).

This extends the standard API tests with comprehensive CDC data validation.

Prerequisites:
- Run test_cdc_matrix.sh first to generate test data
- Unity Catalog Volume with synced test data
- Configuration files: .env/cockroachdb_credentials.json and .env/cockroachdb_pipelines.json

Usage:
    # Run all scenarios
    pytest sources/cockroachdb/test/test_cockroachdb_cdc_scenarios.py -v
    
    # Run with specific test_run_id
    pytest sources/cockroachdb/test/test_cockroachdb_cdc_scenarios.py --test-run-id=1769034791 -v
    
    # Run only JSON scenarios
    pytest sources/cockroachdb/test/test_cockroachdb_cdc_scenarios.py -k json -v
"""

import pytest
import json
import os
import sys
import time
from pathlib import Path
from typing import Dict, Any, List, Optional

# Add parent directories to path
parent_dir = Path(__file__).parent.parent.parent
if str(parent_dir) not in sys.path:
    sys.path.insert(0, str(parent_dir))

from sources.cockroachdb.test_log_manager import (
    TestLogManager,
    CDCTestReport,
    CDCTestResult
)
from sources.cockroachdb.cockroachdb import (
    LakeflowConnect,
    ConnectorMode,
    load_crdb_config,
    load_and_merge_cdc_to_delta,
    collect_all_records,
    parse_test_scenario
)


# ============================================================================
# Test Configuration
# ============================================================================

# All 8 test scenarios (as generated by test_cdc_matrix.sh)
TEST_SCENARIOS = [
    "test-json_usertable_with_split",
    "test-json_usertable_no_split",
    "test-json_simple_test_with_split",
    "test-json_simple_test_no_split",
    "test-parquet_usertable_with_split",
    "test-parquet_usertable_no_split",
    "test-parquet_simple_test_with_split",
    "test-parquet_simple_test_no_split",
]

# Workload parameters (must match test_cdc_matrix.sh)
SIMPLE_TEST_INITIAL_ROWS = 1000
USERTABLE_INITIAL_ROWS = 10000
WORKLOAD_UPDATE_COUNT = 400
WORKLOAD_INSERT_COUNT = 50
WORKLOAD_DELETE_COUNT = 100


# ============================================================================
# Fixtures
# ============================================================================

@pytest.fixture(scope="session")
def config():
    """Load CockroachDB and pipeline configuration"""
    git_root = Path(__file__).parent.parent.parent.parent
    cockroach_dir = git_root / "sources" / "cockroachdb"
    
    crdb_json = cockroach_dir / ".env" / "cockroachdb_credentials.json"
    pipeline_json = cockroach_dir / ".env" / "cockroachdb_pipelines.json"
    
    if not crdb_json.exists():
        pytest.skip(f"Missing config: {crdb_json}")
    if not pipeline_json.exists():
        pytest.skip(f"Missing config: {pipeline_json}")
    
    crdb_config = load_crdb_config(str(crdb_json))
    
    with open(pipeline_json, 'r') as f:
        pipeline_config = json.load(f)
    
    return {
        'crdb_config': crdb_config,
        'pipeline_config': pipeline_config,
        'catalog': pipeline_config['catalog'],
        'schema': pipeline_config['schema'],
        'volume': pipeline_config['volume_name']
    }


@pytest.fixture(scope="session")
def spark():
    """Get Spark session (requires Databricks Connect or Databricks environment)"""
    try:
        # Try to get existing Spark session
        from pyspark.sql import SparkSession
        spark_session = SparkSession.getActiveSession()
        if spark_session is None:
            pytest.skip("No active Spark session. Run in Databricks or with Databricks Connect.")
        return spark_session
    except ImportError:
        pytest.skip("PySpark not available")


@pytest.fixture(scope="session")
def dbutils(spark):
    """Get dbutils (requires Databricks environment)"""
    try:
        from pyspark.dbutils import DBUtils
        return DBUtils(spark)
    except ImportError:
        pytest.skip("dbutils not available. Run in Databricks environment.")


@pytest.fixture(scope="session")
def test_run_id(request, config, dbutils):
    """
    Get test_run_id (timestamp) to use.
    Can be overridden with --test-run-id pytest option.
    """
    # Check for command-line override
    test_run_id = request.config.getoption("--test-run-id", default=None)
    
    if test_run_id:
        return test_run_id
    
    # Otherwise, find latest test run from logs
    log_manager = TestLogManager(
        config['catalog'],
        config['schema'],
        config['volume'],
        dbutils
    )
    
    test_runs = log_manager.list_test_runs()
    
    if not test_runs:
        pytest.skip("No test runs found. Run test_cdc_matrix.sh first to generate test data.")
    
    return test_runs[0]  # Latest


@pytest.fixture(scope="session")
def log_manager(config, dbutils):
    """Create TestLogManager for reading/writing results"""
    return TestLogManager(
        config['catalog'],
        config['schema'],
        config['volume'],
        dbutils
    )


@pytest.fixture(scope="session")
def cdc_report(test_run_id, log_manager):
    """
    Load existing CDC report from test_cdc_matrix.sh or create new one.
    This report will be updated with notebook test results.
    """
    report = log_manager.read_report(test_run_id)
    
    if report is None:
        # Create new report if test_cdc_matrix.sh didn't run
        report = log_manager.create_report(
            test_run_id=test_run_id,
            test_runner="pytest"
        )
    else:
        # Update test_runner to indicate notebook tests are being added
        report.test_runner = f"{report.test_runner} + pytest"
    
    yield report
    
    # Save report after all tests complete
    log_manager.compute_summary(report)
    log_manager.write_report(report)
    log_manager.print_report(report, show_details=True)


def pytest_addoption(parser):
    """Add custom pytest options"""
    parser.addoption(
        "--test-run-id",
        action="store",
        default=None,
        help="Test run ID (timestamp) to use. If not specified, uses latest."
    )


# ============================================================================
# Test Class
# ============================================================================

class TestCockroachDBCDCScenarios:
    """
    Test all CDC scenarios using both Autoloader and Iterator patterns.
    
    This class extends the standard LakeflowConnect tests with comprehensive
    CDC data validation across all format/table/split combinations.
    """
    
    def get_scenario_result(self, report: CDCTestReport, scenario_name: str) -> Optional[CDCTestResult]:
        """Find existing scenario result in report or create new one"""
        for result in report.scenario_results:
            if result.scenario_name == scenario_name:
                return result
        
        # Create new result if not found
        scenario = parse_test_scenario(scenario_name)
        
        # Calculate expected final rows
        if scenario.table_name == "simple_test":
            initial_rows = SIMPLE_TEST_INITIAL_ROWS
        else:
            initial_rows = USERTABLE_INITIAL_ROWS
        
        expected_final_rows = initial_rows + WORKLOAD_INSERT_COUNT - WORKLOAD_DELETE_COUNT
        
        result = CDCTestResult(
            scenario_name=scenario_name,
            format=scenario.format,
            table=scenario.table_name,
            split_option=scenario.split_info,
            expected_final_rows=expected_final_rows
        )
        
        report.scenario_results.append(result)
        return result
    
    @pytest.mark.parametrize("scenario_name", TEST_SCENARIOS)
    def test_autoloader_pattern(
        self,
        scenario_name: str,
        config: Dict[str, Any],
        spark,
        dbutils,
        test_run_id: str,
        cdc_report: CDCTestReport,
        log_manager: TestLogManager
    ):
        """
        Test Autoloader pattern for a CDC scenario.
        
        This test:
        1. Finds the scenario data in Unity Catalog Volume
        2. Runs load_and_merge_cdc_to_delta() (Autoloader)
        3. Validates row count matches expected
        4. Records results in shared log
        """
        # Parse scenario
        scenario = parse_test_scenario(scenario_name)
        
        # Build paths
        catalog = config['catalog']
        schema = config['schema']
        volume = config['volume']
        
        volume_path = f"/Volumes/{catalog}/{schema}/{volume}/{scenario.format}/defaultdb/public/{scenario_name}/{test_run_id}"
        target_table = f"{scenario.table_name}_{scenario_name.replace('-', '_')}_delta"
        target_table_path = f"{catalog}.{schema}.{target_table}"
        
        # Check if data exists
        try:
            files = dbutils.fs.ls(volume_path)
            if not files:
                pytest.skip(f"No data found at {volume_path}")
        except Exception as e:
            pytest.skip(f"Cannot access {volume_path}: {e}")
        
        # Run Autoloader pattern
        start_time = time.time()
        
        try:
            result = load_and_merge_cdc_to_delta(
                source_table=scenario.table_name,
                volume_path=volume_path,
                target_table_path=target_table_path,
                crdb_config=config['crdb_config'],
                catalog="defaultdb",
                schema="public",
                spark=spark,
                dbutils=dbutils,
                clear_checkpoint=True,
                verify=True,
                compare_source=False,  # Skip comparison, we'll validate directly
                debug=False,
                version=0  # Use the timestamped directory
            )
            
            duration = time.time() - start_time
            
            # Validate results
            assert result['success'], f"Autoloader failed: {result}"
            
            # Update scenario result
            scenario_result = self.get_scenario_result(cdc_report, scenario_name)
            scenario_result.autoloader_row_count = result['delta_count']
            scenario_result.autoloader_match_expected = (
                result['delta_count'] == scenario_result.expected_final_rows
            )
            scenario_result.autoloader_duration_seconds = duration
            scenario_result.volume_path = volume_path
            
            # Validate scenario
            log_manager.validate_scenario(scenario_result)
            
            # Assert row count matches expected
            assert result['delta_count'] == scenario_result.expected_final_rows, (
                f"Row count mismatch: expected {scenario_result.expected_final_rows}, "
                f"got {result['delta_count']}"
            )
            
        finally:
            # Clean up Delta table
            try:
                spark.sql(f"DROP TABLE IF EXISTS {target_table_path}")
            except Exception:
                pass
    
    @pytest.mark.parametrize("scenario_name", TEST_SCENARIOS)
    def test_iterator_pattern(
        self,
        scenario_name: str,
        config: Dict[str, Any],
        spark,
        dbutils,
        test_run_id: str,
        cdc_report: CDCTestReport,
        log_manager: TestLogManager
    ):
        """
        Test Iterator pattern for a CDC scenario.
        
        This test:
        1. Finds the scenario data in Unity Catalog Volume
        2. Creates LakeflowConnect in VOLUME mode
        3. Runs collect_all_records() (Iterator)
        4. Validates row count matches expected
        5. Records results in shared log
        """
        # Parse scenario
        scenario = parse_test_scenario(scenario_name)
        
        # Build paths
        catalog = config['catalog']
        schema = config['schema']
        volume = config['volume']
        
        volume_path = f"/Volumes/{catalog}/{schema}/{volume}/{scenario.format}/defaultdb/public/{scenario_name}/{test_run_id}"
        
        # Check if data exists
        try:
            files = dbutils.fs.ls(volume_path)
            if not files:
                pytest.skip(f"No data found at {volume_path}")
        except Exception as e:
            pytest.skip(f"Cannot access {volume_path}: {e}")
        
        # Initialize connector in VOLUME mode
        connector_options = {
            'mode': ConnectorMode.VOLUME.value,
            'volume_path': volume_path,
            'spark': spark,
            'dbutils': dbutils
        }
        
        connector = LakeflowConnect(connector_options)
        
        # Run Iterator pattern
        start_time = time.time()
        
        result = collect_all_records(
            connector=connector,
            table_name=scenario.table_name,
            table_options={},
            max_batches=None,  # No limit for file-based modes
            debug=False
        )
        
        duration = time.time() - start_time
        
        # Update scenario result
        scenario_result = self.get_scenario_result(cdc_report, scenario_name)
        scenario_result.iterator_row_count = len(result['records'])
        scenario_result.iterator_match_expected = (
            len(result['records']) == scenario_result.expected_final_rows
        )
        scenario_result.iterator_duration_seconds = duration
        scenario_result.volume_path = volume_path
        
        # Validate scenario
        log_manager.validate_scenario(scenario_result)
        
        # Assert row count matches expected
        assert len(result['records']) == scenario_result.expected_final_rows, (
            f"Row count mismatch: expected {scenario_result.expected_final_rows}, "
            f"got {len(result['records'])}"
        )
    
    @pytest.mark.parametrize("scenario_name", TEST_SCENARIOS)
    def test_pattern_consistency(
        self,
        scenario_name: str,
        cdc_report: CDCTestReport,
        log_manager: TestLogManager
    ):
        """
        Validate that Autoloader and Iterator patterns produce consistent results.
        
        This test runs AFTER the autoloader and iterator tests complete,
        ensuring both patterns read the same number of rows.
        """
        scenario_result = self.get_scenario_result(cdc_report, scenario_name)
        
        # Skip if either pattern hasn't run yet
        if scenario_result.autoloader_row_count == 0:
            pytest.skip("Autoloader test hasn't run yet")
        if scenario_result.iterator_row_count == 0:
            pytest.skip("Iterator test hasn't run yet")
        
        # Validate consistency
        assert scenario_result.autoloader_row_count == scenario_result.iterator_row_count, (
            f"Pattern mismatch: Autoloader={scenario_result.autoloader_row_count}, "
            f"Iterator={scenario_result.iterator_row_count}"
        )
        
        # Validate both match expected
        assert scenario_result.autoloader_match_expected, "Autoloader doesn't match expected"
        assert scenario_result.iterator_match_expected, "Iterator doesn't match expected"
        
        # Final validation
        log_manager.validate_scenario(scenario_result)
        assert scenario_result.validation_status == "PASS", (
            f"Validation failed: {scenario_result.validation_errors}"
        )


# ============================================================================
# Test Report Hook
# ============================================================================

def pytest_sessionfinish(session, exitstatus):
    """Print final CDC test report after all tests complete"""
    print("\n" + "=" * 80)
    print("CDC TEST SUITE COMPLETED")
    print("=" * 80)
    print(f"Exit status: {exitstatus}")
    print(f"Log saved to: /Volumes/.../test_logs/<timestamp>.json")
    print("=" * 80 + "\n")
